version: 0.2

phases:
  install:
    commands:
      - echo "Installing Serverless Framework"
      - npm install -g serverless
  pre_build:
    commands:
      - echo "-------------------- Branch Detected"
      - |
        if [ "$ENV" == "main" ]; then
          export AWS_PROFILE="transfer-family-dev"
        else
          export AWS_PROFILE="transfer-family-prod"
        fi
      - echo "Using AWS Profile $AWS_PROFILE"
  build:
    commands:
      - echo "Deploying Serverless"
      - npx serverless deploy --aws-profile $AWS_PROFILE
