version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Serverless Framework"
      - npm install -g serverless@3.39.0
  pre_build:
    commands:
      - echo "-------------------- Branch Detected"
      - |
        if [ "$ENV" = "main" ]; then
          export AWS_PROFILE="transfer-family-dev"
        else
          export AWS_PROFILE="transfer-family-prod"
        fi
  build:
    commands:
      - echo "Deploying Serverless"
      - cd serverlessFramework
      - npx serverless deploy --aws-profile $AWS_PROFILE
