version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Serverless Framework"
      - npm install -g serverless@3.39.0

  pre_build:
    commands:
      - echo "-------------------- Branch Detected"
      - echo "ENV value is $ENV"
      - |
        if [ "$ENV" = "main" ]; then
          echo "Main branch detected, deploying to prod stage."
          STAGE="prod"
        else
          echo "Non-main branch detected, deploying to dev stage."
          STAGE="dev"
        fi
      - echo "Using stage $STAGE"

  build:
    commands:
      - echo "Deploying Serverless"
      - echo "Current stage is $STAGE"
      - cd serverlessFramework
      - npx serverless deploy --stage $STAGE
