version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Serverless Framework"
      - npm install -g serverless@3.39.0
  pre_build:
    commands:
      - echo "-------------------- Branch Detected"
      - echo "ENV value is $ENV"  
      - |
        if [ "$ENV" = "main" ]; then
          echo "Main branch detected, not using AWS_PROFILE."
          unset AWS_PROFILE  # Ensuring AWS_PROFILE is not set
        else
          export AWS_PROFILE="transfer-family-prod"
          echo "Using AWS Profile $AWS_PROFILE" 
        fi
  build:
    commands:
      - echo "Deploying Serverless"
      - echo "Current AWS Profile is $AWS_PROFILE"
      - cd serverlessFramework
      - npx serverless deploy ${AWS_PROFILE:+--aws-profile $AWS_PROFILE}